matrix:
  allow_failures:
    - name: "Test Suite - Node.js Nightly build"
    - name: "Linter"
  include:
    - name: "Test Suite + coverage - 12.0.0" #min
      language: node_js
      node_js: 12.0.0
      script: npm run coverage
      after_script: npx codecov
    - name: "Test Suite + coverage - stable"
      language: node_js
      node_js: stable
      script: npm run coverage
      after_script: npx codecov
    - name: "Test Suite - Windows"
      language: node_js
      os: windows
      script: npm test
      node_js: node
    - name: "Test Suite - Electron - 6.0.0"
      language: node_js
      node_js: stable
      script: xvfb-run npx electron@6.0.0 ./test/electron
    - name: "Test Suite - Electron - ^6.0.0"
      language: node_js
      node_js: stable
      script: xvfb-run npx electron@6 ./test/electron
    - name: "Test Suite - Node.js Nightly build"
      language: minimal
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/
      install:
        - nvm i node
        - npm i
      script: npm test
    - name: Linter
      language: node_js
      node_js: stable
      script: npm run lint
