name: NPM Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        prepare-script:
          - browser
          - node-cjs
          - node-esm
          - universal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
          always-auth: true
      - run: npm install --global npm@7
      - name: Load cached dist
        uses: actions/cache@v2
        id: dist
        with:
          path: dist
          key: dist-${{ hashFiles('src/**/*.ts') }}-${{ hashFiles('tsconfig/*.json') }}
      - name: Prepare distribution
        run: node tools/publish-${{ matrix.prepare-script }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
