name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron:  0 9 * * 1-5

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm install
      - run: npm run lint
      - run: npx dtslint --onlyTestTsNext types

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 10.13.0
          - 10
          - 12.0.0
          - 12
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run coverage
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npx codecov

  test-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        electron-version:
          - 6.0.0
          - 6
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm install --global xvfb-maybe electron@${{ matrix.electron-version }}
      - run: npm install
      - run: xvfb-maybe electron ./test/electron
