name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**.md"
      - "tools/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "tools/**"
  pull_request_target:
    paths-ignore:
      - "**.md"
      - "tools/**"
    types:
      - labeled
  schedule:
    - cron: 0 11 * * 1-5
  workflow_dispatch:

jobs:
  unlabel:
    if: ${{ github.event_name == 'pull_request_target' && github.event.label.name == 'full-ci' }}
    runs-on: ubuntu-latest
    steps:
      - run: gh pr edit $PR --repo $REPO --remove-label "full-ci"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.number }}
          REPO: ${{ github.event.repository.full_name }}

  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm clean-install
      - id: cache-key
        run: echo "::set-output name=value::dist-${{ hashFiles('src/**/*.ts') }}-${{ hashFiles('tsconfig/*.json') }}-${{ hashFiles('.github/workflows/*.yml') }}-${{ hashFiles('package-lock.json') }}"
      - name: Cache dist
        uses: actions/cache@v2
        id: dist
        with:
          path: dist
          key: ${{ steps.cache-key.outputs.value }}
      - run: sed -i -e "s/-i ''/-i/g" package.json
      - run: sed -i -e "s/gcp/cp/g" package.json
      - name: Build
        run: npm run build-all
        if: ${{ steps.dist.outputs.cache-hit != 'true' }}
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - run: git reset HEAD --hard

  test:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12
          - 14
          - 16
          - 18

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm clean-install
      - name: Load cached dist
        uses: actions/cache@v2
        id: dist
        with:
          path: dist
          key: ${{ needs.build.outputs.cache-key }}
      - name: Abort if dist isn't cached
        if: ${{ steps.dist.outputs.cache-hit != 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('dist cache hit failed')
      - run: find test -type f -name '*.mjs' -print0 | xargs -0 sed -i -e "s/await import(/require(/g"
        if: ${{ startsWith(matrix.node-version, '12') }}
      - name: Test with Node.js crypto module
        run: npm run test
      - name: Test with Node.js crypto module w/ CryptoKey
        run: npm run test-cryptokey
        if: ${{ !startsWith(matrix.node-version, '14') && !startsWith(matrix.node-version, '12') }}
      - name: Test with Node.js Web Cryptography API
        run: npm run test-webcrypto
        if: ${{ !startsWith(matrix.node-version, '14') && !startsWith(matrix.node-version, '12') }}
      - name: Test with Node.js Web API
        run: npm run test-webapi
        if: ${{ !startsWith(matrix.node-version, '14') && !startsWith(matrix.node-version, '12') }}

  test-deno:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Load cached dist
        uses: actions/cache@v2
        id: dist
        with:
          path: dist
          key: ${{ needs.build.outputs.cache-key }}
      - name: Abort if dist isn't cached
        if: ${{ steps.dist.outputs.cache-hit != 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('dist cache hit failed')
      - name: Test Deno Definitions
        run: deno check dist/deno/index.ts
      - name: Test Deno
        run: npm run test-deno -- --no-check

  test-cloudflare:
    concurrency: test-cloudflare
    if: ${{ !startsWith(github.event_name, 'pull_request') || (github.event_name == 'pull_request_target' && github.event.label.name == 'full-ci') }}
    needs:
      - build
      - test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm clean-install
      - name: Load cached dist
        uses: actions/cache@v2
        id: dist
        with:
          path: dist
          key: ${{ needs.build.outputs.cache-key }}
      - name: Abort if dist isn't cached
        if: ${{ steps.dist.outputs.cache-hit != 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('dist cache hit failed')
      - name: Test Cloudflare Workers
        run: npm run test-cloudflare-workers
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  test-electron:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        electron-version:
          - 12.0.0
          - latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm clean-install
      - name: Load cached dist
        uses: actions/cache@v2
        id: dist
        with:
          path: dist
          key: ${{ needs.build.outputs.cache-key }}
      - name: Abort if dist isn't cached
        if: ${{ steps.dist.outputs.cache-hit != 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('dist cache hit failed')
      - name: Install Electron
        run: npm install --global xvfb-maybe electron@${{ matrix.electron-version }}
      - name: Test Electron crypto
        run: xvfb-maybe electron ./test/.electron

  test-browsers:
    concurrency: test-browsers
    if: ${{ !startsWith(github.event_name, 'pull_request') || (github.event_name == 'pull_request_target' && github.event.label.name == 'full-ci') }}
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm clean-install
      - name: Load cached dist
        uses: actions/cache@v2
        id: dist
        with:
          path: dist
          key: ${{ needs.build.outputs.cache-key }}
      - name: Abort if dist isn't cached
        if: ${{ steps.dist.outputs.cache-hit != 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('dist cache hit failed')
      - run: npx retry-cli npm run test-browsers

  prepare-release:
    needs:
      - test
      - test-browsers
      - test-electron
      - test-deno
      - test-cloudflare
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository == 'panva/jose' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: node tools/release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
